name: Go Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | grep total | awk '{print $3}' > coverage.txt

      - name: Generate coverage badge
        run: |
          COVERAGE=$(cat coverage.txt | tr -d '%')
          curl -o static/coverage-badge.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-brightgreen"
        env:
          COVERAGE: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit badge
        if: github.event_name == 'push'
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add static/coverage-badge.svg
          git commit -m "chore: update test coverage badge" || echo "No changes to commit"
          git push